[package]
name = "tm-html"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description = "Html related features and utilities for tsdm"
rust-version.workspace = true

[dependencies]
select.workspace = true
