stage = "Ending"
registration_path = "raw/00_登记帖"

[reward_policy.complete]
ww = 50
tsb = 100
energy = 2
credit = 10
[reward_policy.missing1]
ww = 40
tsb = 80
energy = 0
credit = 0
[reward_policy.missing2]
ww = 30
tsb = 60
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
thread = [
    { name = "A组", path = "raw/01_初赛_a" },
    { name = "B组", path = "raw/01_初赛_b" },
    { name = "C组", path = "raw/01_初赛_c" },
    { name = "D组", path = "raw/01_初赛_d" },
]
[[round.group]]
thread = [{ name = "结果", path = "raw/01_初赛结果" }]

[[round]]
name = "第二轮"
[[round.group]]
name = "四分之一决赛"
thread = [
    { name = "第1组", path = "raw/02_四分之一决赛_1" },
    { name = "第2组", path = "raw/02_四分之一决赛_2" },
    { name = "第3组", path = "raw/02_四分之一决赛_3" },
    { name = "第4组", path = "raw/02_四分之一决赛_4" },
]
[[round.group]]
thread = [
    { name = "结果", path = "raw/02_四分之一决赛结果" },
]

[[round]]
name = "第三轮"
[[round.group]]
name = "半决赛"
thread = [
    { name = "第1组", path = "raw/03_半决赛_1" },
    { name = "第2组", path = "raw/03_半决赛_2" },
]
[[round.group]]
thread = [
    { name = "排位赛第一场", path = "raw/03_排位赛第一场" },
]
[[round.group]]
thread = [
    { name = "结果", path = "raw/03_半决赛结果" },
]

[[round]]
name = "第四轮"
[[round.group]]
thread = [
    { name = "总决赛", path = "raw/04_总决赛" },
]
[[round.group]]
thread = [
    { name = "排位赛第二场", path = "raw/04_排位赛第二场" },
]
