stage = "Ending"
current_data_path = "path_to_current_data"
registration_path = "raw/00_登记帖"

[reward_policy.complete]
ww = 50
tsb = 100
energy = 2
credit = 10
[reward_policy.missing1]
ww = 40
tsb = 80
energy = 0
credit = 0
[reward_policy.missing2]
ww = 30
tsb = 60
energy = 0
credit = 0

[round."第一轮"]
"初赛A组" = "raw/01_初赛_a"
"初赛B组" = "raw/01_初赛_b"
"初赛C组" = "raw/01_初赛_c"
"初赛D组" = "raw/01_初赛_d"
"初赛结果" = "raw/01_初赛结果"
[round."第二轮"]
"四分之一决赛第1组" = "raw/02_四分之一决赛_1"
"四分之一决赛第2组" = "raw/02_四分之一决赛_2"
"四分之一决赛第3组" = "raw/02_四分之一决赛_3"
"四分之一决赛第4组" = "raw/02_四分之一决赛_4"
"四分之一决赛结果" = "raw/02_四分之一决赛结果"
[round."第三轮"]
"半决赛第1组" = "raw/03_半决赛_1"
"半决赛第2组" = "raw/03_半决赛_1"
"排位赛第一场" = "raw/03_排位赛第一场"
"半决赛结果" = "raw/03_半决赛结果"
[round."第四轮"]
"总决赛" = "raw/04_总决赛"
"排位赛第二场" = "raw/04_排位赛第二场"
