[package]
name = "tm-types"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description = "Definition of common types"
rust-version.workspace = true

[dependencies]
serde.workspace = true
tracing.workspace = true
