[package]
name = "tm-bbcode"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "BBCode parser for tsdm"
rust-version.workspace = true

[dependencies]
