[package]
name = "tm-bbcode-macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
tm-bbcode-webcolor.workspace = true

proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
